# Generated by Django 4.1 on 2022-08-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiration',
            field=models.DateField(),
        ),
    ]
