# Generated by Django 4.1 on 2022-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='type',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(default='Breakfast', max_length=20),
        ),
    ]
