# Generated by Django 4.1 on 2022-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_meal_type_meal_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_ingredients',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(max_length=20),
        ),
    ]
