# Generated by Django 4.1 on 2022-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_meal_meal_ingredients_alter_meal_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day_of_week',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
